#!/bin/sh

# delete_folio_reference_data <OKAPI> <TENANT> <OKAPIUSERNAME> <OKAPIPASSWORD>
# Or set environment variables $OKAPI $TENANT $OKAPIUSERNAME $OKAPIPASSWORD and
# call delete_folio_reference_data without arguments.

set -e

: ${OKAPI:=$1}
: ${OKAPI:=http://localhost:8081}
: ${TENANT:=$2}
: ${TENANT:=diku}
: ${OKAPIUSERNAME:=$3}
: ${OKAPIUSERNAME:=diku_admin}
: ${OKAPIPASSWORD:=$4}
: ${OKAPIPASSWORD:=admin}

COOKIES=$( mktemp --tmpdir cookies.XXXXXXXXXX )
LOGIN=$( jq -n -c --arg username "$OKAPIUSERNAME" --arg password "$OKAPIPASSWORD" '{"username": $username, "password": $password}' )
LOGINRESPONSE=$( curl -w"\n\n" -sS -D - -j -c $COOKIES -H "X-Okapi-Tenant: $TENANT" -H "Content-type: application/json" -d "$LOGIN" $OKAPI/authn/login-with-expiry )
if echo "$LOGINRESPONSE" | head -1 | grep ' 201 '
then
  echo "Login succeeded"
else
  echo "Login failed"
  echo "$LOGINRESPONSE"
  rm "$COOKIES"
  exit 1
fi

process ()
{
  norecord=0
  deleted=0
  failed=0

  while read line
  do
    if [ -z "$line" ]
    then
      continue
    fi
 
    endpoint=$(echo "$line" | cut -f 1)
    id=$(echo "$line" | cut -f 2)
    name=$(echo "$line" | cut -f 3)

    response=$(curl --dump-header dump-header -sS -b $COOKIES -H "X-Okapi-Tenant: $TENANT" -X DELETE "$OKAPI/$endpoint/$id")
    header=$(cat dump-header)
    rm dump-header
    status=$( echo "$header" | head -1 | cut -d ' ' -f 2 )
    case "$status" in
      404)
        echo "$OKAPI/$endpoint/$id ($name) not found on server"
        norecord=$(( norecord + 1 ))
        ;;
      204)
        echo "$OKAPI/$endpoint/$id ($name) deleted"
        deleted=$(( deleted + 1 ))
        ;;
      *)
        echo "$OKAPI/$endpoint/$id ($name) failed:"
        echo "$header"
        echo "$response"
        echo
        failed=$(( failed + 1 ))
        ;;
    esac
  done
  
  echo "$norecord not found on server, $deleted deleted, $failed failed"
}

process < toBeDeleted.tsv

rm $COOKIES
