#!/bin/sh

# insert_local_k10plus <OKAPI> <TENANT> <OKAPIUSERNAME> <OKAPIPASSWORD>
# Or set environment variables $OKAPI $TENANT $OKAPIUSERNAME $OKAPIPASSWORD and
# call insert_local_k10plus without arguments.

set -e

: ${OKAPI:=$1}
: ${OKAPI:=http://localhost:8081}
: ${TENANT:=$2}
: ${TENANT:=diku}
: ${OKAPIUSERNAME:=$3}
: ${OKAPIUSERNAME:=diku_admin}
: ${OKAPIPASSWORD:=$4}
: ${OKAPIPASSWORD:=admin}

TOKEN=$( curl -sS -D - -H "X-Okapi-Tenant: $TENANT" -H "Content-type: application/json" \
  -d "{\"tenant\":\"$TENANT\",\"username\":\"$OKAPIUSERNAME\",\"password\":\"$OKAPIPASSWORD\"}" \
  "$OKAPI/authn/login" \
  | grep -i "^x-okapi-token: " | tr -d "\n\r" )

echo "TOKEN=$TOKEN"

for file in electronic-access-relationships/*.json
do
  echo "$file"
  curl -w"\n" -sS -H "X-Okapi-Tenant: $TENANT" -H "$TOKEN" -H "Content-Type: application/json" \
         -d "@$file" "$OKAPI/electronic-access-relationships"
done

for file in holdings-note-types/*.json
do
  echo "$file"
  curl -w"\n" -sS -H "X-Okapi-Tenant: $TENANT" -H "$TOKEN" -H "Content-Type: application/json" \
         -d "@$file" "$OKAPI/holdings-note-types"
done

for file in instance-note-types/*.json
do
  echo "$file"
  curl -w"\n" -sS -H "X-Okapi-Tenant: $TENANT" -H "$TOKEN" -H "Content-Type: application/json" \
         -d "@$file" "$OKAPI/instance-note-types"
done


for file in instance-relationship-types/*.json
do
  echo "$file"
  curl -w"\n" -sS -H "X-Okapi-Tenant: $TENANT" -H "$TOKEN" -H "Content-Type: application/json" \
         -d "@$file" "$OKAPI/instance-relationship-types"
done
